name: Broken With Purpose
favicon: null
layout_spectrum: 0.10121667454950511
typography_spectrum: 0.9896553680300713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e04823'
    - '#699dc4'
    - '#edede5'
    - '#010101'
    - '#9f7947'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.9391144698020071
purpose: []
